folder: ".."
data_dir: 'data'
tree_small: 'tree152taxa.nwk'
tree_large: 'tree.nwk'

# check if the following executable are available on your system or update the values accordingly
seq-gen: seq-gen

# This command is called in the beginning of every rule and allows to add some command-line configurations if needed
src: echo ""

# This command is called before every python script execution, e.g. it could be used to activate a conda environment
py_config: "source activate pastenv"
